### ISSUE TITLE
Unable to hacktivate iPhone 5 (5,2) on iOS 8.4.1.

### ISSUE THREAD

**Issue by shimmyshimmyya1** [maksimka539/ioshacktivationtool#1]
I went into ramdisk after the first part of the iOS installation, and I tried using the script after I got to the home screen, it kept dropping the same error: `[ERROR] MobileGestalt.plist not found.`

**Comment by maksimka539** [comment]
check new version

**Comment by shimmyshimmyya1** [comment]
Nope, still the same

[ioshacktivationtool.txt](https://github.com/user-attachments/files/23202195/ioshacktivationtool.txt)

**Comment by maksimka539** [comment]
fixed

**Comment by shimmyshimmyya1** [comment]
The new interface is cool, but it still fails to download something from the device.

<img width="697" height="483" alt="Image" src="https://github.com/user-attachments/assets/93e160b2-099f-49ef-ae11-9c9809fc625b" />

UPD: I managed to fix the issue with the script failing to download the file from device. The output says that everything has gone smoothly, but 3uTools says that the device is still not activated.

<img width="697" height="483" alt="Image" src="https://github.com/user-attachments/assets/d036a156-ce3d-405c-a4e2-9887aca65dc1" />

<img width="248" height="111" alt="Image" src="https://github.com/user-attachments/assets/a0174441-10e9-4fef-a01c-9506da5ed18e" />

**Comment by maksimka539** [comment]
please check new version

**Comment by shimmyshimmyya1** [comment]
Works now, thanks a lot!
